### ISSUE TITLE
Ability to provide lock on multiple objects with one Lock file type

### ISSUE THREAD

**Issue by zs-personalize-ai** [petrkotas/k8s-object-lock#2]
Is there a way we can lock multiple objects with one Lock file.

e.g.

```
apiVersion: kotas.tech/v1
kind: Lock
metadata:
  name: lock-nginx-deployment 
spec:
  lock-objects:
   - deployments/dep1
   - deployments/dep2
   - configmaps/cm1
   - services/svc1
```
This will be very useful instead of creating a lock file for every kubernetes object
